export const en = {
  locale: "en",
  nav: {
    products: "Products", industries: "Industries", insights: "Insights", about: "About", quality: "Quality", contact: "Contact",
    requestQuote: "Request a Quote", openMenu: "Open products menu", closeMenu: "Close menu", skipToContent: "Skip to content",
  },
  footer: { insights: "Insights", privacy: "Privacy", terms: "Terms of Use" },
  common: {
    exploreProducts: "Explore Products", learnMore: "Learn more", viewAll: "View all products", requestQuote: "Request a Quote",
    relatedProducts: "Related products", applications: "Typical applications", availableGrades: "Available grades",
    packaging: "Packaging", specifications: "Specifications", specificationsOnRequest: "Contact us to confirm the specification available for the selected material and source.",
    documentationOnRequest: "Ask us which COA, TDS and SDS documents are available for the selected material and source.", backToProducts: "Back to products",
    searchProducts: "Search products", noProducts: "No products match your search.", allCategories: "All categories",
  },
  catalog: {
    eyebrow: "[ CATALOGUE ]",
    title: "Products",
    intro: "Review the current product groups, or send the material name, grade, quantity and application for an unlisted requirement.",
    catalogueLabel: "Product catalogue",
    filterLabel: "Product category filters",
    item: "Item",
    value: "Value",
  },
  home: {
    eyebrow: "Materials for manufacturing / Vietnam", title: "Raw materials and ingredients for manufacturers in Vietnam",
    summary: "MRT Materials receives sourcing enquiries for food ingredients, chemicals and industrial materials. Send the material name, grade or specification, quantity and delivery location for review.",
    marquee: ["SODIUM", "MAGNESIUM", "PET RESIN", "PARAFFIN WAX", "THICKENERS", "MATERIAL SOURCING"],
    categories: { eyebrow: "[ 01 / PRODUCT CATEGORIES ]", title: "Food ingredients, packaging materials and chemicals", body: "The current catalogue covers three product groups. Unlisted materials can be reviewed from a clear specification or reference grade." },
    industries: { eyebrow: "[ 02 / APPLICATIONS ]", title: "Materials by manufacturing application", items: ["Dietary supplements & nutraceuticals", "Food & beverage", "Cosmetics & personal care", "Plastic packaging", "General manufacturing"] },
    process: { eyebrow: "[ 03 / ENQUIRY PROCESS ]", title: "How a sourcing enquiry is handled", steps: [
      { title: "Send material details", body: "Provide the material name or CAS number, application, target grade and specification where available." },
      { title: "Confirm technical requirements", body: "We check the available information and confirm which COA, TDS or SDS documents the proposed source can provide." },
      { title: "Review sourcing options", body: "We confirm quantity, packaging, destination and timing before preparing the quotation." },
      { title: "Quotation and delivery", body: "If the commercial terms are agreed, we confirm the order and delivery details." },
    ] },
    why: { eyebrow: "[ 04 / SCOPE OF REVIEW ]", title: "What we confirm for each sourcing request", items: [
      { title: "Listed and unlisted materials", body: "Use the catalogue as a starting point. For an unlisted material, send the specification or a comparison grade." },
      { title: "Required documents", body: "State which COA, TDS, SDS or internal documents your team requires so availability can be checked for the proposed source." },
      { title: "Quotation details", body: "Grade, quantity, packaging, destination and requested timing are confirmed before a quotation is prepared." },
      { title: "Order and delivery details", body: "After commercial terms are agreed, the order, packaging, destination and delivery information are confirmed." },
    ] },
    featured: { eyebrow: "[ 05 / CURRENT CATALOGUE ]", title: "Selected materials in the current catalogue" },
    cta: { title: "Send a material enquiry", body: "Include the material name, intended use, grade or specification, quantity, required documents and delivery location.", button: "Send material details" },
  },
  industries: {
    eyebrow: "Industries & applications", title: "Materials by manufacturing application", intro: "Browse the catalogue areas connected with each application, then send the exact grade, specification and quantity for review.",
    items: [
      { title: "Dietary supplements & nutraceuticals", body: "Ingredient and excipient enquiries defined by formulation role, target grade and required documents.", categories: ["Nutraceutical & Food Ingredients"] },
      { title: "Food & beverage", body: "Salts, thickeners and stabilisers considered against the food or beverage application and process conditions.", categories: ["Nutraceutical & Food Ingredients"] },
      { title: "Cosmetics & personal care", body: "Thickeners, stabilisers and paraffin wax considered against formulation and manufacturing requirements.", categories: ["Nutraceutical & Food Ingredients", "Industrial & Packaging Materials"] },
      { title: "Plastic packaging", body: "PET bottle-grade and HDPE blow-moulding resin enquiries linked to equipment, mould and finished-container requirements.", categories: ["Industrial & Packaging Materials"] },
      { title: "General manufacturing", body: "Paraffin wax and chemical enquiries reviewed for project-specific applications.", categories: ["Industrial & Packaging Materials", "Chemicals"] },
    ],
  },
  about: { eyebrow: "About MRT Materials", title: "Material sourcing enquiries for manufacturers in Vietnam", body: "MRT Materials reviews requests for ingredients, packaging materials and chemicals, including the required grade, documents, quantity and delivery location.", valuesTitle: "Information used for review", values: ["Requirement-led review", "Document requirements stated early", "Commercial details confirmed before quotation", "Availability confirmed per source"] },
  quality: { eyebrow: "Documents & material review", title: "Documents and checks for each material enquiry", intro: "Each enquiry is reviewed against the material, application, required documents and intended use.", items: [
    { title: "Requirement matching", body: "The material identity, grade, application and critical limits are compared with the information available from a proposed source." },
    { title: "Available documents", body: "Ask which COA, TDS and SDS documents are available for the proposed material and source." },
    { title: "Batch and lot information", body: "Ask which batch or lot details and supporting documents are available for the proposed source and order." },
    { title: "Handling information", body: "Review the current SDS and supplier guidance for storage, transport and handling before use." },
  ], note: "MRT Materials does not make certification claims on this website. Please contact us with your documentation requirements." },
  contact: {
    eyebrow: "Contact / RFQ", title: "Send a material sourcing request", intro: "Send the material name, application, grade or specification, quantity, required documents and delivery location.",
    sales: "Sales", accounts: "Accounts", address: "Address", map: "Open location in OpenStreetMap", phone: "Phone",
    form: { company: "Company name", contactPerson: "Contact person", email: "Email", phone: "Phone", country: "Country", product: "Product / material", grade: "Grade / specification", quantity: "Quantity & unit", deliveryDate: "Target delivery date", message: "Message", submit: "Send request", required: "Required", honeypot: "Leave this field empty", fileNote: "For files or detailed specifications, please email sales@mrtmaterials.com.", success: "Your email draft is ready to send.", error: "Please complete the required fields and provide a valid email address." },
  },
  legal: {
    privacy: { title: "Privacy", updated: "Last updated: 18 September 2026", intro: "This notice explains how MRT Materials handles information submitted through this website.", sections: [
      { title: "Information you provide", body: "We may receive the contact and request details you choose to send through the contact form or by email." },
      { title: "How information is used", body: "Information is used to review and respond to business enquiries, including requests for quotations." },
      { title: "Contact", body: "For privacy-related enquiries, contact sales@mrtmaterials.com." },
    ] },
    terms: { title: "Terms of Use", updated: "Last updated: 18 September 2026", intro: "By using this website, you agree to use its information for lawful business purposes.", sections: [
      { title: "Information on this website", body: "Catalogue information is provided for general business reference. Availability and documentation are subject to review for each request." },
      { title: "No offer", body: "Website content does not constitute a binding offer to supply any material." },
      { title: "Contact", body: "Contact MRT Materials to discuss a specific material requirement." },
    ] },
  },
  notFound: { eyebrow: "404", title: "Page not found", body: "The requested page is unavailable or may have moved.", button: "Return home" },
  seo: { siteName: "MRT Materials", defaultDescription: "Raw materials, ingredients, chemicals and industrial materials for manufacturers in Vietnam." },
} as const;
