export const vi = {
  locale: "vi",
  nav: {
    products: "Sản phẩm", industries: "Ứng dụng", insights: "Kiến thức", about: "Giới thiệu", quality: "Tài liệu", contact: "Liên hệ",
    requestQuote: "Yêu cầu báo giá", openMenu: "Mở menu sản phẩm", closeMenu: "Đóng menu", skipToContent: "Chuyển đến nội dung",
  },
  footer: { insights: "Kiến thức", privacy: "Chính sách bảo mật", terms: "Điều khoản sử dụng" },
  common: {
    exploreProducts: "Khám phá sản phẩm", learnMore: "Tìm hiểu thêm", viewAll: "Xem tất cả sản phẩm", requestQuote: "Yêu cầu báo giá",
    relatedProducts: "Sản phẩm liên quan", applications: "Ứng dụng tiêu biểu", availableGrades: "Phân hạng hiện có",
    packaging: "Quy cách đóng gói", specifications: "Thông số", specificationsOnRequest: "Liên hệ để xác nhận thông số hiện có của nguyên liệu và nguồn hàng được lựa chọn.",
    documentationOnRequest: "Hãy nêu bộ tài liệu cần thiết để chúng tôi kiểm tra COA, TDS và SDS hiện có của nguyên liệu và nguồn hàng cụ thể.", backToProducts: "Quay lại sản phẩm",
    searchProducts: "Tìm kiếm sản phẩm", noProducts: "Không có sản phẩm phù hợp với tìm kiếm của bạn.", allCategories: "Tất cả danh mục",
  },
  catalog: {
    eyebrow: "[ DANH MỤC ]",
    title: "Sản phẩm",
    intro: "Xem các nhóm sản phẩm hiện có, hoặc gửi tên nguyên liệu, grade, số lượng và ứng dụng đối với yêu cầu ngoài danh mục.",
    catalogueLabel: "Danh mục sản phẩm",
    filterLabel: "Bộ lọc nhóm sản phẩm",
    item: "Hạng mục",
    value: "Giá trị",
  },
  home: {
    eyebrow: "Nguyên liệu cho sản xuất / Việt Nam", title: "Nguyên liệu và vật liệu cho doanh nghiệp sản xuất tại Việt Nam",
    summary: "MRT Materials tiếp nhận yêu cầu tìm nguồn nguyên liệu thực phẩm, hóa chất và vật liệu công nghiệp. Gửi tên sản phẩm, grade hoặc thông số, số lượng và địa điểm giao hàng để chúng tôi rà soát.",
    marquee: ["NATRI", "MAGIÊ", "NHỰA PET", "SÁP PARAFFIN", "CHẤT LÀM ĐẶC", "TÌM NGUỒN NGUYÊN LIỆU"],
    categories: { eyebrow: "[ 01 / NHÓM SẢN PHẨM ]", title: "Nguyên liệu thực phẩm, vật liệu bao bì và hóa chất", body: "Danh mục hiện có gồm ba nhóm sản phẩm. Với nguyên liệu ngoài danh mục, hãy gửi thông số hoặc grade tham chiếu để rà soát." },
    industries: { eyebrow: "[ 02 / ỨNG DỤNG ]", title: "Nhóm vật liệu theo ứng dụng sản xuất", items: ["Thực phẩm bảo vệ sức khỏe & dinh dưỡng", "Thực phẩm & đồ uống", "Mỹ phẩm & chăm sóc cá nhân", "Bao bì nhựa", "Sản xuất công nghiệp"] },
    process: { eyebrow: "[ 03 / QUY TRÌNH YÊU CẦU ]", title: "Quy trình xử lý yêu cầu tìm nguồn", steps: [
      { title: "Gửi thông tin nguyên liệu", body: "Cung cấp tên nguyên liệu hoặc số CAS, ứng dụng, grade mục tiêu và thông số hiện có." },
      { title: "Xác nhận yêu cầu kỹ thuật", body: "Chúng tôi kiểm tra thông tin hiện có và xác nhận COA, TDS hoặc SDS nào có thể được cung cấp từ nguồn được đề xuất." },
      { title: "Rà soát phương án cung ứng", body: "Hai bên xác nhận số lượng, bao bì, điểm giao và thời gian dự kiến trước khi chuẩn bị báo giá." },
      { title: "Báo giá và giao nhận", body: "Nếu các điều kiện thương mại được thống nhất, hai bên xác nhận thông tin đặt hàng và giao nhận." },
    ] },
    why: { eyebrow: "[ 04 / PHẠM VI RÀ SOÁT ]", title: "Những thông tin được xác nhận cho từng yêu cầu tìm nguồn", items: [
      { title: "Vật liệu trong và ngoài danh mục", body: "Danh mục là điểm bắt đầu. Với vật liệu chưa được liệt kê, hãy gửi thông số hoặc grade tham chiếu." },
      { title: "Bộ tài liệu cần thiết", body: "Nêu rõ COA, TDS, SDS hoặc tài liệu nội bộ cần thiết để kiểm tra khả năng cung cấp từ nguồn được đề xuất." },
      { title: "Thông tin báo giá", body: "Grade, số lượng, bao bì, điểm giao và thời gian dự kiến được xác nhận trước khi chuẩn bị báo giá." },
      { title: "Thông tin đặt hàng và giao nhận", body: "Sau khi thống nhất điều kiện thương mại, hai bên xác nhận đơn hàng, bao bì, điểm giao và thông tin giao nhận." },
    ] },
    featured: { eyebrow: "[ 05 / DANH MỤC HIỆN TẠI ]", title: "Một số sản phẩm trong danh mục hiện tại" },
    cta: { title: "Gửi yêu cầu nguyên liệu", body: "Cung cấp tên nguyên liệu, mục đích sử dụng, grade hoặc thông số, số lượng, bộ tài liệu và địa điểm giao hàng.", button: "Gửi thông tin nguyên liệu" },
  },
  industries: {
    eyebrow: "Ngành & ứng dụng", title: "Nhóm vật liệu theo ứng dụng sản xuất", intro: "Xem nhóm danh mục liên quan đến từng ứng dụng, sau đó gửi grade, thông số và số lượng cần rà soát.",
    items: [
      { title: "Thực phẩm bảo vệ sức khỏe & dinh dưỡng", body: "Yêu cầu nguyên liệu và tá dược được xác định theo vai trò trong công thức, grade mục tiêu và bộ tài liệu.", categories: ["Nguyên liệu thực phẩm & dinh dưỡng"] },
      { title: "Thực phẩm & đồ uống", body: "Các dòng muối, chất làm đặc và ổn định được xem xét theo ứng dụng thực phẩm, đồ uống và điều kiện quy trình.", categories: ["Nguyên liệu thực phẩm & dinh dưỡng"] },
      { title: "Mỹ phẩm & chăm sóc cá nhân", body: "Chất làm đặc, chất ổn định và sáp paraffin được xem xét theo công thức và yêu cầu sản xuất.", categories: ["Nguyên liệu thực phẩm & dinh dưỡng", "Vật liệu công nghiệp & bao bì"] },
      { title: "Bao bì nhựa", body: "Yêu cầu PET chai và HDPE thổi khuôn được gắn với thiết bị, khuôn và yêu cầu bao bì thành phẩm.", categories: ["Vật liệu công nghiệp & bao bì"] },
      { title: "Sản xuất công nghiệp", body: "Yêu cầu sáp paraffin và hóa chất được rà soát theo ứng dụng cụ thể của từng dự án.", categories: ["Vật liệu công nghiệp & bao bì", "Hóa chất"] },
    ],
  },
  about: { eyebrow: "Về MRT Materials", title: "Tiếp nhận yêu cầu tìm nguồn nguyên liệu cho doanh nghiệp sản xuất tại Việt Nam", body: "MRT Materials rà soát yêu cầu về nguyên liệu thực phẩm, vật liệu bao bì và hóa chất theo grade, bộ tài liệu, số lượng và điểm giao.", valuesTitle: "Thông tin dùng để rà soát", values: ["Rà soát theo yêu cầu cụ thể", "Nêu bộ tài liệu từ đầu", "Xác nhận thông tin thương mại trước báo giá", "Xác nhận khả năng cung ứng theo từng nguồn"] },
  quality: { eyebrow: "Tài liệu & rà soát nguyên liệu", title: "Tài liệu và nội dung cần kiểm tra cho từng yêu cầu nguyên liệu", intro: "Mỗi yêu cầu được rà soát theo nguyên liệu, ứng dụng, bộ tài liệu cần thiết và mục đích sử dụng.", items: [
    { title: "Đối chiếu yêu cầu", body: "Định danh, grade, ứng dụng và giới hạn quan trọng được đối chiếu với thông tin hiện có của nguồn được đề xuất." },
    { title: "Tài liệu hiện có", body: "Hãy xác nhận COA, TDS và SDS nào hiện có cho nguyên liệu và nguồn được đề xuất." },
    { title: "Thông tin batch và lô", body: "Xác nhận thông tin batch, lô và tài liệu nào hiện có cho nguồn hàng và đơn hàng được đề xuất." },
    { title: "Thông tin lưu kho và xử lý", body: "Xem SDS hiện hành và hướng dẫn của nhà cung cấp về lưu kho, vận chuyển và xử lý trước khi sử dụng." },
  ], note: "MRT Materials không đưa ra tuyên bố chứng nhận trên website này. Vui lòng liên hệ để trao đổi yêu cầu về tài liệu của Quý khách." },
  contact: {
    eyebrow: "Liên hệ / RFQ", title: "Gửi yêu cầu tìm nguồn nguyên liệu", intro: "Gửi tên nguyên liệu, ứng dụng, grade hoặc thông số, số lượng, bộ tài liệu cần thiết và điểm giao.",
    sales: "Kinh doanh", accounts: "Kế toán", address: "Địa chỉ", map: "Mở vị trí trên OpenStreetMap", phone: "Điện thoại",
    form: { company: "Tên công ty", contactPerson: "Người liên hệ", email: "Email", phone: "Điện thoại", country: "Quốc gia", product: "Sản phẩm / nguyên liệu", grade: "Phân hạng / thông số", quantity: "Số lượng & đơn vị", deliveryDate: "Ngày giao hàng dự kiến", message: "Nội dung", submit: "Gửi yêu cầu", required: "Bắt buộc", honeypot: "Không điền vào trường này", fileNote: "Đối với tệp đính kèm hoặc thông số chi tiết, vui lòng gửi về sales@mrtmaterials.com.", success: "Bản nháp email của Quý khách đã sẵn sàng để gửi.", error: "Vui lòng hoàn tất các trường bắt buộc và cung cấp email hợp lệ." },
  },
  legal: {
    privacy: { title: "Chính sách bảo mật", updated: "Cập nhật lần cuối: 18/09/2026", intro: "Thông báo này giải thích cách MRT Materials xử lý thông tin được gửi qua website.", sections: [
      { title: "Thông tin Quý khách cung cấp", body: "Chúng tôi có thể tiếp nhận thông tin liên hệ và nội dung yêu cầu do Quý khách tự nguyện gửi qua biểu mẫu hoặc email." },
      { title: "Mục đích sử dụng thông tin", body: "Thông tin được sử dụng để xem xét và phản hồi các yêu cầu kinh doanh, bao gồm yêu cầu báo giá." },
      { title: "Liên hệ", body: "Vui lòng liên hệ sales@mrtmaterials.com đối với các vấn đề liên quan đến bảo mật." },
    ] },
    terms: { title: "Điều khoản sử dụng", updated: "Cập nhật lần cuối: 18/09/2026", intro: "Khi sử dụng website này, Quý khách đồng ý sử dụng thông tin cho mục đích kinh doanh hợp pháp.", sections: [
      { title: "Thông tin trên website", body: "Thông tin danh mục được cung cấp để tham khảo trong hoạt động kinh doanh. Khả năng cung ứng và tài liệu sẽ được xem xét theo từng yêu cầu." },
      { title: "Không phải chào bán", body: "Nội dung trên website không cấu thành cam kết chào bán bất kỳ nguyên liệu nào." },
      { title: "Liên hệ", body: "Vui lòng liên hệ MRT Materials để trao đổi về nhu cầu nguyên liệu cụ thể." },
    ] },
  },
  notFound: { eyebrow: "404", title: "Không tìm thấy trang", body: "Trang được yêu cầu không khả dụng hoặc đã được chuyển sang địa chỉ khác.", button: "Về trang chủ" },
  seo: { siteName: "MRT Materials", defaultDescription: "Nguyên liệu, hóa chất và vật liệu công nghiệp cho các nhà sản xuất tại Việt Nam." },
} as const;
