export const vi = {
  locale: "vi",
  nav: {
    products: "Sản phẩm", industries: "Ngành hàng", insights: "Kiến thức", about: "Giới thiệu", quality: "Chất lượng", contact: "Liên hệ",
    requestQuote: "Yêu cầu báo giá", openMenu: "Mở menu sản phẩm", closeMenu: "Đóng menu", skipToContent: "Chuyển đến nội dung",
  },
  footer: { insights: "Kiến thức", privacy: "Chính sách bảo mật", terms: "Điều khoản sử dụng" },
  common: {
    exploreProducts: "Khám phá sản phẩm", learnMore: "Tìm hiểu thêm", viewAll: "Xem tất cả sản phẩm", requestQuote: "Yêu cầu báo giá",
    relatedProducts: "Sản phẩm liên quan", applications: "Ứng dụng tiêu biểu", availableGrades: "Phân hạng hiện có",
    packaging: "Quy cách đóng gói", specifications: "Thông số", specificationsOnRequest: "Thông số kỹ thuật được cung cấp theo yêu cầu.",
    documentationOnRequest: "Tài liệu như COA, SDS và TDS được cung cấp theo yêu cầu.", backToProducts: "Quay lại sản phẩm",
    searchProducts: "Tìm kiếm sản phẩm", noProducts: "Không có sản phẩm phù hợp với tìm kiếm của bạn.", allCategories: "Tất cả danh mục",
  },
  catalog: {
    eyebrow: "[ DANH MỤC ]",
    title: "Sản phẩm",
    intro: "Khám phá các nhóm nguyên liệu hiện có hoặc gửi yêu cầu cho một nhu cầu cụ thể.",
    catalogueLabel: "Danh mục sản phẩm",
    filterLabel: "Bộ lọc nhóm sản phẩm",
    item: "Hạng mục",
    value: "Giá trị",
  },
  home: {
    eyebrow: "Tìm nguồn nguyên liệu / Việt Nam", title: "Tìm đúng nguyên liệu, rõ thông tin ngay từ đầu.",
    summary: "Cho chúng tôi biết sản phẩm bạn đang làm, grade hoặc tiêu chí cần đạt và nơi giao hàng. MRT Materials sẽ cùng đội ngũ của bạn xem xét phương án phù hợp.",
    marquee: ["NATRI", "MAGIÊ", "NHỰA PET", "SÁP PARAFFIN", "CHẤT LÀM ĐẶC", "TÌM NGUỒN NGUYÊN LIỆU"],
    categories: { eyebrow: "[ 01 / DANH MỤC ]", title: "Bạn đang cần tìm nguyên liệu nào?", body: "Bắt đầu từ ba nhóm chính dưới đây, hoặc gửi cho chúng tôi một yêu cầu cụ thể." },
    industries: { eyebrow: "[ 02 / NGÀNH HÀNG ]", title: "Mỗi ngành sản xuất có một bài toán khác nhau.", items: ["Thực phẩm bảo vệ sức khỏe & dinh dưỡng", "Thực phẩm & đồ uống", "Mỹ phẩm & chăm sóc cá nhân", "Bao bì nhựa", "Sản xuất công nghiệp"] },
    process: { eyebrow: "[ 03 / QUY TRÌNH ]", title: "Sau khi bạn gửi yêu cầu, chúng tôi làm gì?", steps: [
      { title: "Tiếp nhận yêu cầu", body: "Bạn gửi tên nguyên liệu, ứng dụng, grade hoặc thông số đang cần." },
      { title: "Rà soát thông tin", body: "Chúng tôi kiểm tra thông tin hiện có và phối hợp COA, TDS hoặc SDS nếu nguồn hàng có thể cung cấp." },
      { title: "Chuẩn bị báo giá", body: "Hai bên làm rõ số lượng, bao bì, điểm giao và thời gian dự kiến trước khi báo giá." },
      { title: "Phối hợp giao hàng", body: "Khi phương án được thống nhất, chúng tôi theo sát các bước giao nhận tiếp theo." },
    ] },
    why: { eyebrow: "[ 04 / MRT MATERIALS ]", title: "Một đầu mối để theo sát yêu cầu của bạn.", items: [
      { title: "Tìm nguồn theo nhu cầu", body: "Danh mục là điểm bắt đầu. Nếu chưa có vật liệu bạn cần, hãy gửi thông số để chúng tôi xem xét." },
      { title: "Tài liệu rõ ràng", body: "Nêu ngay COA, TDS, SDS hoặc tài liệu nội bộ bạn cần để tránh phải trao đổi nhiều vòng." },
      { title: "Báo giá đủ căn cứ", body: "Grade, số lượng, bao bì, địa điểm và thời gian giao hàng được làm rõ trước khi chuẩn bị báo giá." },
      { title: "Theo sát giao nhận", body: "Các thông tin đã thống nhất được giữ xuyên suốt từ yêu cầu ban đầu đến giao hàng." },
    ] },
    featured: { eyebrow: "[ 05 / SẢN PHẨM NỔI BẬT ]", title: "Một số vật liệu có thể bắt đầu trao đổi ngay." },
    cta: { title: "Chưa thấy đúng vật liệu bạn cần?", body: "Gửi tên sản phẩm, grade tham chiếu hoặc thông số hiện có. Chúng tôi sẽ phản hồi những điểm cần làm rõ để tiếp tục.", button: "Gửi yêu cầu" },
  },
  industries: {
    eyebrow: "Ngành hàng", title: "Vật liệu phù hợp với nhu cầu của nhà sản xuất.", intro: "Chúng tôi hỗ trợ trao đổi nhu cầu tìm nguồn trong các lĩnh vực sau.",
    items: [
      { title: "Thực phẩm bảo vệ sức khỏe & dinh dưỡng", body: "Nguyên liệu và tá dược phục vụ các hoạt động sản xuất phù hợp.", categories: ["Nguyên liệu thực phẩm & dinh dưỡng"] },
      { title: "Thực phẩm & đồ uống", body: "Các nguyên liệu được lựa chọn cho ứng dụng sản xuất thực phẩm và đồ uống.", categories: ["Nguyên liệu thực phẩm & dinh dưỡng"] },
      { title: "Mỹ phẩm & chăm sóc cá nhân", body: "Vật liệu cho yêu cầu công thức và sản xuất liên quan.", categories: ["Nguyên liệu thực phẩm & dinh dưỡng", "Vật liệu công nghiệp & bao bì"] },
      { title: "Bao bì nhựa", body: "Tìm nguồn nhựa cho chai, thổi khuôn và nhu cầu bao bì.", categories: ["Vật liệu công nghiệp & bao bì"] },
      { title: "Sản xuất công nghiệp", body: "Vật liệu và hóa chất được xem xét theo nhu cầu sản xuất từng dự án.", categories: ["Vật liệu công nghiệp & bao bì", "Hóa chất"] },
    ],
  },
  about: { eyebrow: "Về MRT Materials", title: "Đối tác tìm nguồn nguyên liệu tại Việt Nam.", body: "MRT Materials tiếp nhận và xem xét nhu cầu tìm nguồn nguyên liệu, hóa chất và vật liệu công nghiệp của doanh nghiệp sản xuất.", valuesTitle: "Cách chúng tôi làm việc", values: ["Chất lượng", "Minh bạch", "Phản hồi kịp thời", "Hợp tác dài hạn"] },
  quality: { eyebrow: "Chất lượng & tuân thủ", title: "Tiếp cận cẩn trọng với thông tin nguyên liệu.", intro: "Chúng tôi hỗ trợ quy trình xem xét thực tế cho từng nhu cầu tìm nguồn.", items: [
    { title: "Đánh giá nguồn cung", body: "Nguồn cung được xem xét dựa trên yêu cầu đã chia sẻ đối với từng nguyên liệu." },
    { title: "Tài liệu theo yêu cầu", body: "COA, SDS và TDS hiện có có thể được phối hợp cung cấp để xem xét theo yêu cầu." },
    { title: "Truy xuất lô hàng", body: "Thông tin lô hàng phù hợp được trao đổi trong phạm vi tài liệu hiện có cho đơn hàng." },
    { title: "Lưu kho & xử lý", body: "Các lưu ý về lưu kho và xử lý có thể được trao đổi tùy theo yêu cầu nguyên liệu." },
  ], note: "MRT Materials không đưa ra tuyên bố chứng nhận trên website này. Vui lòng liên hệ để trao đổi yêu cầu về tài liệu của Quý khách." },
  contact: {
    eyebrow: "Liên hệ / RFQ", title: "Hãy cho chúng tôi biết nhu cầu của bộ phận sản xuất.", intro: "Vui lòng cung cấp các thông tin hiện có; chúng tôi sẽ xem xét yêu cầu của Quý khách.",
    sales: "Kinh doanh", accounts: "Kế toán", address: "Địa chỉ", map: "Mở vị trí trên OpenStreetMap", phone: "Điện thoại",
    form: { company: "Tên công ty", contactPerson: "Người liên hệ", email: "Email", phone: "Điện thoại", country: "Quốc gia", product: "Sản phẩm / nguyên liệu", grade: "Phân hạng / thông số", quantity: "Số lượng & đơn vị", deliveryDate: "Ngày giao hàng dự kiến", message: "Nội dung", submit: "Gửi yêu cầu", required: "Bắt buộc", honeypot: "Không điền vào trường này", fileNote: "Đối với tệp đính kèm hoặc thông số chi tiết, vui lòng gửi về sales@mrtmaterials.com.", success: "Bản nháp email của Quý khách đã sẵn sàng để gửi.", error: "Vui lòng hoàn tất các trường bắt buộc và cung cấp email hợp lệ." },
  },
  legal: {
    privacy: { title: "Chính sách bảo mật", updated: "Cập nhật lần cuối: 18/09/2026", intro: "Thông báo này giải thích cách MRT Materials xử lý thông tin được gửi qua website.", sections: [
      { title: "Thông tin Quý khách cung cấp", body: "Chúng tôi có thể tiếp nhận thông tin liên hệ và nội dung yêu cầu do Quý khách tự nguyện gửi qua biểu mẫu hoặc email." },
      { title: "Mục đích sử dụng thông tin", body: "Thông tin được sử dụng để xem xét và phản hồi các yêu cầu kinh doanh, bao gồm yêu cầu báo giá." },
      { title: "Liên hệ", body: "Vui lòng liên hệ sales@mrtmaterials.com đối với các vấn đề liên quan đến bảo mật." },
    ] },
    terms: { title: "Điều khoản sử dụng", updated: "Cập nhật lần cuối: 18/09/2026", intro: "Khi sử dụng website này, Quý khách đồng ý sử dụng thông tin cho mục đích kinh doanh hợp pháp.", sections: [
      { title: "Thông tin trên website", body: "Thông tin danh mục được cung cấp để tham khảo trong hoạt động kinh doanh. Khả năng cung ứng và tài liệu sẽ được xem xét theo từng yêu cầu." },
      { title: "Không phải chào bán", body: "Nội dung trên website không cấu thành cam kết chào bán bất kỳ nguyên liệu nào." },
      { title: "Liên hệ", body: "Vui lòng liên hệ MRT Materials để trao đổi về nhu cầu nguyên liệu cụ thể." },
    ] },
  },
  notFound: { eyebrow: "404", title: "Phân tử này đã trôi ngoài phạm vi.", body: "Trang Quý khách tìm kiếm hiện không khả dụng.", button: "Về trang chủ" },
  seo: { siteName: "MRT Materials", defaultDescription: "Nguyên liệu, hóa chất và vật liệu công nghiệp cho các nhà sản xuất tại Việt Nam." },
} as const;
